name: Databricks Template
description: Databricks Template
title: "[Databricks]: "
assignees: []
labels: [databricks]
body:
  - type: textarea
    id: what-pr-do
    attributes:
      label: What does this Pull Request do?
      description: Please put the action here for this PR
    validations:
      required: true
  - type: textarea
    id: why-pr
    attributes:
      label: What is the reasoning behind it?
      description: Please put the purpose here why you raise this PR
    validations:
      required: true
  - type: checkboxes
    id: databricks_resources
    attributes:
      description: Databricks resources to provision
      options:
        - label: Interactive Cluster
          required: false
        - label: Group, User & Service Principal
          required: false
        - label: Instance Pool
          required: false
        - label: Cluster Policy
          required: false
        - label: Secret Scope & Secret
          required: false
        - label: Job
          required: false
        - label: Personal Access Token
          required: false
  - type: markdown
    attributes:
      value: |
        * [Databricks Onboarding Documentation for Provisioning Resources](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/3351183454/Onboarding+Guide+to+Databricks+Workspace)
        * [Databricks Personal Access Token](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/1626249646/Creating+Databricks+token+in+terraform)
        * [Getting Access to Databricks Workspace for Group & User](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/3223131425/Getting+Access+to+Databricks+Workspace)
        * [Create Service Principal](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/1620704192/Create+Service+Principal+Terraform)
