name: Databricks Template
description: Databricks Template
title: "[Databricks]: "
labels: [Databricks]
assignees: []
body:
  - type: textarea
    id: what-pr-do
    attributes:
      label: What does this Pull Request do?
      description: Please put the action here for this PR
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the reasoning behind it?
      description: Please put the purpose here why you raise this PR
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is the reasoning behind it?
      description: Please put the purpose here why you raise this PR
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Interactive Cluster
      description: Interactive Cluster
      options:
        - label: Interactive Cluster
          required: false
  - type: checkboxes
    attributes:
      label: Group, User & Service Principal
      description: Group, User & Service Principal
      options:
        - label: Group, User & Service Principal
          required: false
  - type: checkboxes
    attributes:
      label: Instance Pool
      description: Instance Pool
      options:
        - label: Instance Pool
          required: false
  - type: checkboxes
    attributes:
      label: Cluster Policy
      description: Cluster Policy
      options:
        - label: Cluster Policy
          required: false
  - type: checkboxes
    attributes:
      label: Secret Scope & Secret
      description: Secret Scope & Secret
      options:
        - label: Secret Scope & Secret
          required: false
  - type: checkboxes
    attributes:
      label: Job
      description: Job
      options:
        - label: Job
          required: false
  - type: checkboxes
    attributes:
      label: Personal Access Token
      description: Personal Access Token
      options:
        - label: Personal Access Token
          required: false
  - type: textarea
    attributes:
      label: Reference Documentation
      description: You can refer the following documentations for provision resource.
      placeholder: |
        * [Databricks Onboarding Documentation for Provisioning Resources](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/3351183454/Onboarding+Guide+to+Databricks+Workspace)
        * [Databricks Personal Access Token](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/1626249646/Creating+Databricks+token+in+terraform)
        * [Getting Access to Databricks Workspace for Group & User](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/3223131425/Getting+Access+to+Databricks+Workspace)
        * [Create Service Principal](https://farfetch.atlassian.net/wiki/spaces/DataStrategy/pages/1620704192/Create+Service+Principal+Terraform)
      render: markdown
    validations:
      required: false
